server:
  port: 8082

api:
  urls:
    user: https://reqres.in/api/users/
    posts: https://68700b7f7ca4d06b34b5d3a8.mockapi.io/hamed/api/user/hamed
    camunda: http://localhost:8081/engine-rest
    #camunda: http://host.docker.internal:8081/engine-rest

errors:
  messages:
    USER_NOT_FOUND: "کاربر پیدا نشد"
    INVALID_EMAIL: "ایمیل نامعتبر است"
    GENERAL_ERROR: "خطای عمومی رخ داده است"
